// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.skytrain.nano;

// enum GroupServiceType
public interface GroupServiceType {
  public static final int GroupServiceTypeUnSetting = 0;
  public static final int GroupServiceTypeAirport = 1;
  public static final int GroupServiceTypeTrain = 2;
}
