// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.skytrain.nano;

// enum NodeType
public interface NodeType {
  public static final int NodeTypeUnSetting = 0;
  public static final int NodeTypeCancel = 50;
  public static final int NodeTypeSvr = 100;
  public static final int NodeTypeSvrVipHall = 110;
  public static final int NodeTypeSvrBoarding = 120;
  public static final int NodeTypeSvrVipChannel = 130;
  public static final int NodeTypeDeptAirport = 150;
  public static final int NodeTypeCheckIn = 170;
  public static final int NodeTypeGate = 200;
  public static final int NodeTypeFly = 300;
  public static final int NodeTypeLand = 400;
  public static final int NodeTypeBaggage = 500;
  public static final int NodeTypeClaims = 600;
}
