// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.skytrain.nano;

// enum OrderIdentity
public interface OrderIdentity {
  public static final int UnOrder = 0;
  public static final int BigOrder = 1;
  public static final int FinnalOrder = 2;
}
