// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.skytrain.nano;

// enum PaymentTravelOrderStatus
public interface PaymentTravelOrderStatus {
  public static final int UnSet = 0;
  public static final int UnPay = 10;
  public static final int Paying = 20;
  public static final int PaySuccessed = 30;
  public static final int PayFailed = 40;
}
