// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.skytrain.nano;

// enum TravelType
public interface TravelType {
  public static final int UnSetting = 0;
  public static final int AirportTravel = 1;
  public static final int RailportTravel = 2;
  public static final int VipHall = 3;
  public static final int Boarding = 4;
  public static final int VipChannel = 5;
  public static final int VVipHall = 6;
  public static final int Assistant = 7;
  public static final int CombinedOrder = 128;
}
