// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.skytrain.nano;

// enum VIPHallServiceType
public interface VIPHallServiceType {
  public static final int ServiceTypeVIPHall = 0;
  public static final int ServiceTypeSendAirport = 1;
  public static final int ServiceTypePickAirport = 2;
}
