// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.nano;

// enum AppSource
public interface AppSource {
  public static final int NoSetting = 0;
  public static final int AirwayKeeper = 1;
  public static final int Jsj = 2;
  public static final int Crm = 3;
}
