// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.coremodellib.model.proto.nano;

// enum DataCommission
public interface DataCommission {
  public static final int DataCommissionNoSetting = 0;
  public static final int Personal = 1;
  public static final int Department = 2;
  public static final int DepartmentAndSub = 3;
  public static final int All = 4;
}
