// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.servers1.bean.nano;

@SuppressWarnings("hiding")
public final class BaseResponse extends
    com.google.protobuf.nano.android.ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final android.os.Parcelable.Creator<BaseResponse> CREATOR =
      new com.google.protobuf.nano.android.ParcelableMessageNanoCreator<
          BaseResponse>(BaseResponse.class);

  private static volatile BaseResponse[] _emptyArray;
  public static BaseResponse[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new BaseResponse[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional bool IsSuccess = 1 [default = false];
  public boolean isSuccess;

  // optional string ErrorMessage = 2;
  public java.lang.String errorMessage;

  // optional string ErrorCode = 3;
  public java.lang.String errorCode;

  // optional string NowTime = 4;
  public java.lang.String nowTime;

  public BaseResponse() {
    clear();
  }

  public BaseResponse clear() {
    isSuccess = false;
    errorMessage = "";
    errorCode = "";
    nowTime = "";
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.isSuccess != false) {
      output.writeBool(1, this.isSuccess);
    }
    if (!this.errorMessage.equals("")) {
      output.writeString(2, this.errorMessage);
    }
    if (!this.errorCode.equals("")) {
      output.writeString(3, this.errorCode);
    }
    if (!this.nowTime.equals("")) {
      output.writeString(4, this.nowTime);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.isSuccess != false) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeBoolSize(1, this.isSuccess);
    }
    if (!this.errorMessage.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.errorMessage);
    }
    if (!this.errorCode.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.errorCode);
    }
    if (!this.nowTime.equals("")) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(4, this.nowTime);
    }
    return size;
  }

  @Override
  public BaseResponse mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 8: {
          this.isSuccess = input.readBool();
          break;
        }
        case 18: {
          this.errorMessage = input.readString();
          break;
        }
        case 26: {
          this.errorCode = input.readString();
          break;
        }
        case 34: {
          this.nowTime = input.readString();
          break;
        }
      }
    }
  }

  public static BaseResponse parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new BaseResponse(), data);
  }

  public static BaseResponse parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new BaseResponse().mergeFrom(input);
  }
}
