// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.servers1.bean.nano;

@SuppressWarnings("hiding")
public final class GetTravels2Response extends
    com.google.protobuf.nano.android.ParcelableMessageNano {

  // Used by Parcelable
  @SuppressWarnings({"unused"})
  public static final android.os.Parcelable.Creator<GetTravels2Response> CREATOR =
      new com.google.protobuf.nano.android.ParcelableMessageNanoCreator<
          GetTravels2Response>(GetTravels2Response.class);

  private static volatile GetTravels2Response[] _emptyArray;
  public static GetTravels2Response[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new GetTravels2Response[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional .BaseResponse BaseResponse = 1;
  public gctraveltools.jsj.com.cn.servers1.bean.nano.BaseResponse baseResponse;

  // repeated .TravelDto2 TravelDto2s = 2;
  public gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2[] travelDto2S;

  // optional int32 TotalCount = 3 [default = 0];
  public int totalCount;

  public GetTravels2Response() {
    clear();
  }

  public GetTravels2Response clear() {
    baseResponse = new gctraveltools.jsj.com.cn.servers1.bean.nano.BaseResponse();
    travelDto2S = gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2.emptyArray();
    totalCount = 0;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (this.baseResponse != null) {
      output.writeMessage(1, this.baseResponse);
    }
    if (this.travelDto2S != null && this.travelDto2S.length > 0) {
      for (int i = 0; i < this.travelDto2S.length; i++) {
        gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2 element = this.travelDto2S[i];
        if (element != null) {
          output.writeMessage(2, element);
        }
      }
    }
    if (this.totalCount != 0) {
      output.writeInt32(3, this.totalCount);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (this.baseResponse != null) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(1, this.baseResponse);
    }
    if (this.travelDto2S != null && this.travelDto2S.length > 0) {
      for (int i = 0; i < this.travelDto2S.length; i++) {
        gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2 element = this.travelDto2S[i];
        if (element != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, element);
        }
      }
    }
    if (this.totalCount != 0) {
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.totalCount);
    }
    return size;
  }

  @Override
  public GetTravels2Response mergeFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          if (this.baseResponse == null) {
            this.baseResponse = new gctraveltools.jsj.com.cn.servers1.bean.nano.BaseResponse();
          }
          input.readMessage(this.baseResponse);
          break;
        }
        case 18: {
          int arrayLength = com.google.protobuf.nano.WireFormatNano
              .getRepeatedFieldArrayLength(input, 18);
          int i = this.travelDto2S == null ? 0 : this.travelDto2S.length;
          gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2[] newArray =
              new gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2[i + arrayLength];
          if (i != 0) {
            java.lang.System.arraycopy(this.travelDto2S, 0, newArray, 0, i);
          }
          for (; i < newArray.length - 1; i++) {
            newArray[i] = new gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2();
            input.readMessage(newArray[i]);
            input.readTag();
          }
          // Last one without readTag.
          newArray[i] = new gctraveltools.jsj.com.cn.servers1.bean.nano.TravelDto2();
          input.readMessage(newArray[i]);
          this.travelDto2S = newArray;
          break;
        }
        case 24: {
          this.totalCount = input.readInt32();
          break;
        }
      }
    }
  }

  public static GetTravels2Response parseFrom(byte[] data)
      throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
    return com.google.protobuf.nano.MessageNano.mergeFrom(new GetTravels2Response(), data);
  }

  public static GetTravels2Response parseFrom(
          com.google.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new GetTravels2Response().mergeFrom(input);
  }
}
