// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.servers1.bean.nano;

// enum LanguageVersion
public interface LanguageVersion {
  public static final int CN = 0;
  public static final int EN = 1;
}
