// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.servers1.bean.nano;

// enum SourceWay
public interface SourceWay {
  public static final int SourceWayNoSetting = 0;
  public static final int Web = 10;
  public static final int Wap = 20;
  public static final int IOS = 30;
  public static final int Android = 40;
  public static final int CRM_p = 50;
  public static final int BusinessTravel = 60;
  public static final int WeChat = 70;
  public static final int WeChatProgram = 80;
}
