// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.servers1.bean.nano;

// enum TravelRouteType
public interface TravelRouteType {
  public static final int TravelRouteTypeUnSetting = 0;
  public static final int TravelRouteTypeSys = 1;
  public static final int TravelRouteTypeCus = 2;
}
