// Generated by the protocol buffer compiler.  DO NOT EDIT!

package gctraveltools.jsj.com.cn.servers1.bean.nano;

// enum VIPHallType
public interface VIPHallType {
  public static final int VIPHallTypeUnSetting = 0;
  public static final int VIPHallTypeSelf = 1;
  public static final int VIPHallTypePartner = 2;
  public static final int VIPHallTypeVvip = 3;
}
